version: 2.1
defaults: &defaults
  working_directory: /root/app
  docker:
    - image: google/cloud-sdk
activate-sa: &activate-sa
  - run:
      name: "Activate SA to the Project"
      command: |
        source .circleci/cicd-definitions.sh
        echo ${DODRONES_GCP_MY_LABS_SA} > ${GCLOUD_JSON_KEY_PATH}
        gcloud auth activate-service-account --key-file=${GCLOUD_JSON_KEY_PATH}
        gcloud config set project ${GCLOUD_PROJECT_ID}
revoke-sa: &revoke-sa
  - run:
      name: "Revoke SA"
      command: |
        source .circleci/cicd-definitions.sh
        echo ${DODRONES_GCP_MY_LABS_SA} > ${GCLOUD_JSON_KEY_PATH}
        echo "${GCLOUD_JSON_KEY_PATH}" grep "client_email" | awk '{print $2}' | grep -o '".*"' | sed 's/"//g'
        gcloud auth revoke devops-sa@construtora-2020.iam.gserviceaccount.com

only-releasable: &only-releasable
  filters:
    branches:
      only:
        - release/gcp
non-releasable: &non-releasable
  filters:
    branches:
      ignore:
        - release/gcp

jobs:
  Prepare Credentials:
    <<: *defaults
    steps:
      - checkout
      - <<: *activate-sa

  GCP Sync:
    <<: *defaults
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - <<: *activate-sa
      - run:
          name: "GCP Sync to Bucket"
          command: |
            source .circleci/cicd-definitions.sh
            gsutil -m rsync -c -x '^.*git.*$|^.*circleci.*$|^.*cloud.*$' -r ./ gs://${GCLOUD_PROJECT_BUCKET_NAME}/
  
  GCP Bucket Update:
    <<: *defaults
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - <<: *activate-sa
      - run:
          name: "GCP Bucket Update"
          command: |
            source .circleci/cicd-definitions.sh
            gsutil acl ch -u AllUsers:R gs://${GCLOUD_PROJECT_BUCKET_NAME}/index.html
  
  GCP Publish Site:
    <<: *defaults
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - <<: *activate-sa
      - run:
          name: "GCP Publish Site"
          command: |
            source .circleci/cicd-definitions.sh
            gsutil web set -m index.html gs://${GCLOUD_PROJECT_BUCKET_NAME}

  GCP Revoke Credentials:
    <<: *defaults
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - <<: *revoke-sa

workflows:
  version: 2.1
  
  gcloud_workflow:
    jobs:
      - Prepare Credentials
      - GCP Sync:
          <<: *only-releasable
          requires:
            - Prepare Credentials
      - GCP Bucket Update:
          <<: *only-releasable
          requires:
            - GCP Sync
      - GCP Publish Site:
          <<: *only-releasable
          requires:
            - GCP Bucket Update
